insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Nie',3.5,'Nie','Nie','Suchy');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Nie',4,'Tak','Nie','Z cukrem pudrem');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Nie',5,'Nie','Tak','Z polewą');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Nie',5.5,'Tak','Tak','Z polewą i cukrem pudrem');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Tak',6,'Nie','Nie','Z owocami');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Nie',6,'Nie','Nie','Ze śmietaną');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Nie','Tak',6.5,'Tak','Nie','Z owocami i cukrem pudrem');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Nie',6.5,'Tak','Nie','Ze śmietaną i cukrem pudrem');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Nie',7.5,'Nie','Tak','Ze śmietaną i polewą');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Tak',8.5,'Nie','Nie','Ze śmietaną i owocami');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Tak',9,'Tak','Nie','Ze śmietaną, owocami i cukrem pudrem');
insert into Waffle(cream,fruit,price,sugar,topping,type) values('Tak','Tak',10,'Nie','Tak','Ze śmietaną, owocami i polewą');
